apiVersion: v1
kind: Secret
metadata:
  name: {{ template "jenkins-app.fullname" . }}
  namespace: {{ template "jenkins-app.namespace" . }}
type: Opaque
data:
  password: {{ template "jenkins-app.password" . }}
